# Generated by Django 5.1.1 on 2024-10-11 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('matricula', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidoM', models.CharField(blank=True, max_length=30)),
                ('apellidoP', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('idRegistroDiario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('horaEntrada', models.DateTimeField()),
                ('horaSalida', models.DateTimeField()),
                ('horasDiaria', models.IntegerField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAlServicioSocial',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaDeFinalizacion', models.DateTimeField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_servicio_social', to='users.usuario')),
            ],
        ),
    ]
