# Generated by Django 5.1.1 on 2024-10-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='updated_at',
        ),
    ]
