# Generated by Django 5.1.1 on 2024-11-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usuario_created_at_remove_usuario_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='semestre',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
