# Generated by Django 5.1.1 on 2024-11-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiario',
            name='horaSalida',
            field=models.DateTimeField(blank=True),
        ),
    ]
